export default {
  TOGGLE_FEED: "TOGGLE_FEED",
  RAW_FEED: "RAW_FEED",
  PING: "PING",
  SUPPORTED_PINGS: "SUPPORTED_PINGS",
  SELECT_USER: "SELECT_USER",
  CLEAR_USER: "CLEAR_USER",
  UPDATE_VIEWPORT: "UPDATE_VIEWPORT",
  UPDATE_USER_POSITION: "UPDATE_USER_POSITION",
}